# Generated by Django 4.1.7 on 2023-02-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('desc', models.CharField(max_length=500, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Full Name')),
                ('occupation', models.CharField(max_length=255, null=True, verbose_name='Occupation')),
                ('dateOfTravel', models.DateField(null=True, verbose_name='Date of Travel')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('desc', models.CharField(max_length=500, null=True, verbose_name='Description')),
            ],
        ),
    ]
