# Generated by Django 4.1.7 on 2023-02-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.CharField(max_length=255, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='link',
            field=models.CharField(max_length=255, null=True, verbose_name='Link'),
        ),
    ]
