# Generated by Django 4.1.7 on 2023-02-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_service_link_remove_testimony_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimony',
            new_name='Review',
        ),
    ]
