# Generated by Django 4.1.7 on 2023-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_testimony_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500, null=True, verbose_name='About')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=14, null=True, verbose_name='Contact Number')),
                ('address', models.CharField(max_length=500, null=True, verbose_name='Address')),
            ],
        ),
    ]
